image: dlp

stages:
- cours
- tme

TME7:
  stage: cours
  script: >
    /home/dlp/run.sh -id ILP3 -name ILP3
    com.paracamplus.ilp3.ilp3tme7.test.InterpreterTest
  artifacts:
    reports:
      junit: report.xml
